// frontend-upcontent-react/src/components/Organizations.tsx
import { useEffect, useState } from "react";
import { api, OrgSummary } from "../api";
import { useTokenGetter } from "../useApi";

// Organizations: create, list (filtered to caller server-side), invite.
export default function Organizations() {
  const getToken = useTokenGetter();
  const [orgs, setOrgs] = useState<OrgSummary[]>([]);
  const [slug, setSlug] = useState("");
  const [displayName, setDisplayName] = useState("");
  const [inviteOrg, setInviteOrg] = useState("");
  const [email, setEmail] = useState("");
  const [msg, setMsg] = useState<{ kind: string; text: string } | null>(null);

  const reload = async () => setOrgs(await api.listOrgs(getToken));
  useEffect(() => {
    reload().catch((e) => setMsg({ kind: "error", text: e.message }));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [getToken]);

  const create = async () => {
    try {
      await api.createOrg(getToken, slug, displayName);
      setMsg({ kind: "success", text: `Created organization "${displayName}".` });
      setSlug("");
      setDisplayName("");
      await reload();
    } catch (e: any) {
      setMsg({ kind: "error", text: e.message });
    }
  };

  const invite = async () => {
    try {
      await api.invite(getToken, inviteOrg, email);
      setMsg({ kind: "success", text: `Invitation sent to ${email}.` });
      setEmail("");
    } catch (e: any) {
      setMsg({ kind: "error", text: e.message });
    }
  };

  return (
    <main className="page-main">
      <header className="page-header">
        <h1 className="page-title">Organization</h1>
        <p className="page-sub">Create organizations and invite team members.</p>
      </header>

      {msg && <div className={`alert alert-${msg.kind}`}>{msg.text}</div>}

      <div className="two-col">
        {/* Create organization */}
        <section className="card">
          <div className="card-header">
            <div className="card-icon">🏢</div>
            <h2 className="card-title">Create organization</h2>
            <p className="card-sub">Set up a new Auth0 organization for your team.</p>
          </div>
          <div className="form-stack">
            <div className="form-group">
              <label className="form-label" htmlFor="displayName">
                Display name
              </label>
              <input
                className="form-input"
                id="displayName"
                value={displayName}
                onChange={(e) => setDisplayName(e.target.value)}
                placeholder="Acme Corporation"
              />
              <span className="form-hint">Shown to users in Auth0</span>
            </div>
            <div className="form-group">
              <label className="form-label" htmlFor="orgName">
                Organization ID (slug)
              </label>
              <input
                className="form-input"
                id="orgName"
                value={slug}
                onChange={(e) => setSlug(e.target.value)}
                placeholder="acme-corp"
              />
              <span className="form-hint">
                Lowercase, hyphens only — used in Auth0 URLs
              </span>
            </div>
            <button className="btn btn-primary btn-full" onClick={create}>
              Create organization
            </button>
          </div>
        </section>

        {/* Invite a member */}
        <section className="card">
          <div className="card-header">
            <div className="card-icon">✉️</div>
            <h2 className="card-title">Invite a member</h2>
            <p className="card-sub">Send an Auth0 invitation email to a team member.</p>
          </div>
          <div className="form-stack">
            <div className="form-group">
              <label className="form-label" htmlFor="orgSelect">
                Select organization
              </label>
              <select
                className="form-input form-select"
                id="orgSelect"
                value={inviteOrg}
                onChange={(e) => setInviteOrg(e.target.value)}
              >
                <option value="" disabled>
                  Choose an organization…
                </option>
                {orgs.map((o) => (
                  <option key={o.id} value={o.id}>
                    {o.display_name || o.name}
                  </option>
                ))}
              </select>
              {orgs.length === 0 && (
                <span className="form-hint">
                  No organizations yet — create one first.
                </span>
              )}
            </div>
            <div className="form-group">
              <label className="form-label" htmlFor="inviteEmail">
                Email address
              </label>
              <input
                className="form-input"
                id="inviteEmail"
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="colleague@example.com"
              />
              <span className="form-hint">
                An invitation email will be sent via Auth0
              </span>
            </div>
            <button
              className="btn btn-primary btn-full"
              disabled={!inviteOrg}
              onClick={invite}
            >
              Send invitation
            </button>
          </div>
        </section>
      </div>

      {/* Existing organizations */}
      {orgs.length > 0 && (
        <section className="card card-wide">
          <div className="card-header">
            <div className="card-icon">📋</div>
            <h2 className="card-title">Existing organizations</h2>
          </div>
          <table className="data-table">
            <thead>
              <tr>
                <th>Display name</th>
                <th>Slug</th>
                <th>Auth0 ID</th>
                <th>Plan</th>
              </tr>
            </thead>
            <tbody>
              {orgs.map((o) => (
                <tr key={o.id}>
                  <td>{o.display_name || "—"}</td>
                  <td>
                    <code>{o.name}</code>
                  </td>
                  <td>
                    <code>{o.id}</code>
                  </td>
                  <td>{o.selected_plan || "—"}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>
      )}
    </main>
  );
}

// frontend-sniply-vue/src/components/Organizations.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";
import { api, type OrgSummary } from "../api";
import { useTokenGetter } from "../useToken";

const getToken = useTokenGetter();
const orgs = ref<OrgSummary[]>([]);
const slug = ref("");
const displayName = ref("");
const inviteOrg = ref("");
const email = ref("");
const msg = ref<{ kind: string; text: string } | null>(null);

async function reload() {
  orgs.value = await api.listOrgs(getToken);
}
onMounted(() => reload().catch((e) => (msg.value = { kind: "error", text: e.message })));

async function create() {
  try {
    await api.createOrg(getToken, slug.value, displayName.value);
    msg.value = { kind: "success", text: `Created organization "${displayName.value}".` };
    slug.value = "";
    displayName.value = "";
    await reload();
  } catch (e: any) {
    msg.value = { kind: "error", text: e.message };
  }
}

async function invite() {
  try {
    await api.invite(getToken, inviteOrg.value, email.value);
    msg.value = { kind: "success", text: `Invitation sent to ${email.value}.` };
    email.value = "";
  } catch (e: any) {
    msg.value = { kind: "error", text: e.message };
  }
}
</script>

<template>
  <main class="page-main">
    <header class="page-header">
      <h1 class="page-title">Organization</h1>
      <p class="page-sub">Create organizations and invite team members.</p>
    </header>

    <div v-if="msg" :class="`alert alert-${msg.kind}`">{{ msg.text }}</div>

    <div class="two-col">
      <section class="card">
        <div class="card-header">
          <div class="card-icon">🏢</div>
          <h2 class="card-title">Create organization</h2>
          <p class="card-sub">Set up a new Auth0 organization for your team.</p>
        </div>
        <div class="form-stack">
          <div class="form-group">
            <label class="form-label" for="displayName">Display name</label>
            <input
              id="displayName"
              v-model="displayName"
              class="form-input"
              placeholder="Acme Corporation"
            />
            <span class="form-hint">Shown to users in Auth0</span>
          </div>
          <div class="form-group">
            <label class="form-label" for="orgName">Organization ID (slug)</label>
            <input
              id="orgName"
              v-model="slug"
              class="form-input"
              placeholder="acme-corp"
            />
            <span class="form-hint">Lowercase, hyphens only — used in Auth0 URLs</span>
          </div>
          <button class="btn btn-primary btn-full" @click="create">
            Create organization
          </button>
        </div>
      </section>

      <section class="card">
        <div class="card-header">
          <div class="card-icon">✉️</div>
          <h2 class="card-title">Invite a member</h2>
          <p class="card-sub">Send an Auth0 invitation email to a team member.</p>
        </div>
        <div class="form-stack">
          <div class="form-group">
            <label class="form-label" for="orgSelect">Select organization</label>
            <select id="orgSelect" v-model="inviteOrg" class="form-input form-select">
              <option value="" disabled>Choose an organization…</option>
              <option v-for="o in orgs" :key="o.id" :value="o.id">
                {{ o.display_name || o.name }}
              </option>
            </select>
            <span v-if="orgs.length === 0" class="form-hint">
              No organizations yet — create one first.
            </span>
          </div>
          <div class="form-group">
            <label class="form-label" for="inviteEmail">Email address</label>
            <input
              id="inviteEmail"
              v-model="email"
              type="email"
              class="form-input"
              placeholder="colleague@example.com"
            />
            <span class="form-hint">An invitation email will be sent via Auth0</span>
          </div>
          <button
            class="btn btn-primary btn-full"
            :disabled="!inviteOrg"
            @click="invite"
          >
            Send invitation
          </button>
        </div>
      </section>
    </div>

    <section v-if="orgs.length > 0" class="card card-wide">
      <div class="card-header">
        <div class="card-icon">📋</div>
        <h2 class="card-title">Existing organizations</h2>
      </div>
      <table class="data-table">
        <thead>
          <tr>
            <th>Display name</th>
            <th>Slug</th>
            <th>Auth0 ID</th>
            <th>Plan</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="o in orgs" :key="o.id">
            <td>{{ o.display_name || "—" }}</td>
            <td><code>{{ o.name }}</code></td>
            <td><code>{{ o.id }}</code></td>
            <td>{{ o.selected_plan || "—" }}</td>
          </tr>
        </tbody>
      </table>
    </section>
  </main>
</template>
