// frontend-sniply-vue/src/components/Landing.vue
<script setup lang="ts">
import { useAuth0 } from "@auth0/auth0-vue";

// Sniply landing — editorial hero.
// Preview cards tease plan tiers. Always a DEMO (banner + ribbon).
const { loginWithRedirect } = useAuth0();

const previewPlans = [
  { label: "Starter", price: "$0", per: "/mo", featured: false },
  { label: "Professional", price: "$29", per: "/mo", featured: true },
  { label: "Enterprise", price: "Custom", per: "", featured: false },
];
</script>

<template>
  <main class="hero">
    <div class="hero-content">
      <span class="eyebrow">Welcome to Sniply</span>
      <h1 class="hero-title">
        Add a call-to-action to every link<br />
        <em>convert every share</em>
      </h1>
      <p class="hero-sub">
        Overlay your CTA on any link, track clicks, and manage campaigns across
        every brand and organization you run.
      </p>
      <button class="btn btn-hero" @click="loginWithRedirect()">
        Get started →
      </button>
    </div>

    <div class="hero-cards">
      <div
        v-for="p in previewPlans"
        :key="p.label"
        :class="`preview-card${p.featured ? ' featured' : ''}`"
      >
        <span class="preview-label">{{ p.label }}</span>
        <span class="preview-price">
          {{ p.price }}<span v-if="p.per">{{ p.per }}</span>
        </span>
      </div>
    </div>
  </main>
</template>

// frontend-sniply-react/src/components/Landing.tsx
import { useEffect, useState } from "react";
import { useAuth0 } from "@auth0/auth0-react";
import { API_BASE_URL } from "../auth-config";

// Sniply landing — editorial hero.
// Teaser cards show the REAL plan catalog from the API. Always a DEMO (banner + ribbon).
interface Plan {
  id: string;
  display_name: string;
  description: string;
  price: string;
}

export default function Landing() {
  const { loginWithRedirect } = useAuth0();
  const [plans, setPlans] = useState<Plan[]>([]);

  useEffect(() => {
    // Best-effort fetch of the real catalog. If it fails, render no teaser cards.
    (async () => {
      try {
        const res = await fetch(`${API_BASE_URL}/api/plans`);
        if (res.ok) {
          setPlans((await res.json()) as Plan[]);
        }
      } catch {
        /* render nothing for the teaser */
      }
    })();
  }, []);

  return (
    <main className="hero">
      <div className="hero-content">
        <span className="eyebrow">Welcome to Sniply</span>
        <h1 className="hero-title">
          Add a call-to-action to every link
          <br />
          <em>convert every share</em>
        </h1>
        <p className="hero-sub">
          Overlay your CTA on any link, track clicks, and manage campaigns
          across every brand and organization you run.
        </p>
        <button className="btn btn-hero" onClick={() => loginWithRedirect()}>
          Get started →
        </button>
      </div>

      <div className="hero-cards">
        {plans.map((p, i) => (
          <div
            className={`preview-card${i === 1 ? " featured" : ""}`}
            key={p.id}
          >
            <span className="preview-label">{p.display_name}</span>
            <span className="preview-price">{p.price}</span>
          </div>
        ))}
      </div>
    </main>
  );
}
