// frontend-sniply-vue/src/components/Landing.vue
<script setup lang="ts">
import { useAuth0 } from "@auth0/auth0-vue";

// Sniply landing — editorial hero mirroring the Java reference home page.
// Preview cards tease plan tiers. Always a DEMO (banner + ribbon).
const { loginWithRedirect } = useAuth0();

const previewPlans = [
  { label: "Starter", price: "$0", per: "/mo", featured: false },
  { label: "Professional", price: "$29", per: "/mo", featured: true },
  { label: "Enterprise", price: "Custom", per: "", featured: false },
];
</script>

<template>
  <main class="hero">
    <div class="hero-content">
      <span class="eyebrow">Welcome to Sniply</span>
      <h1 class="hero-title">
        Add a call-to-action to every link<br />
        <em>convert every share</em>
      </h1>
      <p class="hero-sub">
        Overlay your CTA on any link, track clicks, and manage campaigns across
        every brand and organization you run.
      </p>
      <button class="btn btn-hero" @click="loginWithRedirect()">
        Get started →
      </button>
    </div>

    <div class="hero-cards">
      <div
        v-for="p in previewPlans"
        :key="p.label"
        :class="`preview-card${p.featured ? ' featured' : ''}`"
      >
        <span class="preview-label">{{ p.label }}</span>
        <span class="preview-price">
          {{ p.price }}<span v-if="p.per">{{ p.per }}</span>
        </span>
      </div>
    </div>
  </main>
</template>

// frontend-upcontent-react/src/components/Landing.tsx
import { useAuth0 } from "@auth0/auth0-react";

// UpContent landing — editorial hero mirroring the Java reference home page.
// The preview cards show plan tiers as a teaser. Always a DEMO (banner + ribbon).
const PREVIEW_PLANS = [
  { label: "Starter", price: "$0", per: "/mo", featured: false },
  { label: "Professional", price: "$29", per: "/mo", featured: true },
  { label: "Enterprise", price: "Custom", per: "", featured: false },
];

export default function Landing() {
  const { loginWithRedirect } = useAuth0();
  return (
    <main className="hero">
      <div className="hero-content">
        <span className="eyebrow">Welcome to UpContent</span>
        <h1 className="hero-title">
          UpContent turns content into action
          <br />
          <em>spark a conversation</em>
        </h1>
        <p className="hero-sub">
          Manage your organization, assign roles, and invite your team — all in
          one place.
        </p>
        <button className="btn btn-hero" onClick={() => loginWithRedirect()}>
          Get started →
        </button>
      </div>

      <div className="hero-cards">
        {PREVIEW_PLANS.map((p) => (
          <div
            className={`preview-card${p.featured ? " featured" : ""}`}
            key={p.label}
          >
            <span className="preview-label">{p.label}</span>
            <span className="preview-price">
              {p.price}
              {p.per && <span>{p.per}</span>}
            </span>
          </div>
        ))}
      </div>
    </main>
  );
}
